name: Despliegue en Surge.sh

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Instalar Surge (versión estable)
        run: npm install -g surge@latest

      - name: Desplegar en Surge
        run: surge --project ./ --domain ${{ secrets.SURGE_DOMAIN }}.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
