name: Despliegue en Surge.sh

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Surge
        run: npm install -g surge@latest

      - name: Desplegar
        run: surge ./ --domain ${{ secrets.SURGE_DOMAIN }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
