echo 'name: Despliegue en Surge.sh

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Instalar Surge
      run: npm install -g surge
      
    - name: Desplegar en Surge
      run: surge ./ --domain ${{ secrets.SURGE_DOMAIN }}.surge.sh
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}' > .github/workflows/main.yaml
